using System;
using System.IO;
using System.Text;
using EpanetSharp.Core;

namespace EpanetSharp.Reporting
{
    /// <summary>
    /// Gera relatórios de resultados de uma simulação do EPANET utilizando a API nativa.
    /// Fornece operações para gerar, salvar e limpar relatórios.
    /// </summary>
    public sealed class Report
    {
        private readonly Project _project;
        private readonly StringBuilder _buffer = new();
        public ReportOptions Options { get; }

        public Report(Project project, ReportOptions? options = null)
        {
            _project = project ?? throw new ArgumentNullException(nameof(project));
            Options = options ?? new ReportOptions();
        }

        /// <summary>
        /// Gera o relatório atual preenchendo o buffer interno. Utiliza valores lidos via NativeContext
        /// (por exemplo, energia, nós e enlaces) quando o projeto nativo está disponível.
        /// </summary>
        public void Generate()
        {
            _buffer.Clear();
            _buffer.AppendLine("EPANET Report Generated by EpanetSharp");
            _buffer.AppendLine($"Timestamp: {DateTime.UtcNow:u}");

            if (!Project.IsNativeAvailable())
            {
                _buffer.AppendLine("Native EPANET library not available; report contains no simulation results.");
                return;
            }

            // Summary
            _buffer.AppendLine();
            _buffer.AppendLine("== Summary ==");
            _buffer.AppendLine($"Nodes: {_project.Network.NodeCount}, Links: {_project.Network.LinkCount}, Controls: {_project.Network.ControlCount}");

            if (Options.IncludeEnergy)
            {
                _buffer.AppendLine();
                _buffer.AppendLine("== Energy ==");
                // Example: iterate links and sum EN_LINK_ENERGY where available
                double totalEnergy = 0.0;
                if (Project.IsNativeAvailable())
                {
                    var ctx = _project.NativeContext;
                    int linkCount = _project.Network.LinkCount;
                    for (int i = 1; i <= linkCount; i++)
                    {
                        try
                        {
                            double e = ctx.GetLinkValue(i, Native.NativeConstants.EN_LINK_ENERGY);
                            totalEnergy += e;
                        }
                        catch { }
                    }
                }
                _buffer.AppendLine($"Total Energy: {totalEnergy}");
            }

            if (Options.IncludeNodes)
            {
                _buffer.AppendLine();
                _buffer.AppendLine("== Nodes ==");
                if (Project.IsNativeAvailable())
                {
                    var ctx = _project.NativeContext;
                    int nCount = _project.Network.NodeCount;
                    for (int i = 1; i <= nCount; i++)
                    {
                        try
                        {
                            string id = ctx.GetNodeId(i);
                            double head = ctx.GetNodeValue(i, Native.NativeConstants.EN_HEAD);
                            double pressure = ctx.GetNodeValue(i, Native.NativeConstants.EN_PRESSURE);
                            _buffer.AppendLine($"{id}: Head={head}, Pressure={pressure}");
                        }
                        catch { }
                    }
                }
            }

            if (Options.IncludeLinks)
            {
                _buffer.AppendLine();
                _buffer.AppendLine("== Links ==");
                if (Project.IsNativeAvailable())
                {
                    var ctx = _project.NativeContext;
                    int lCount = _project.Network.LinkCount;
                    for (int i = 1; i <= lCount; i++)
                    {
                        try
                        {
                            string id = ctx.GetLinkId(i);
                            double flow = ctx.GetLinkValue(i, Native.NativeConstants.EN_LINK_FLOW);
                            double headloss = ctx.GetLinkValue(i, Native.NativeConstants.EN_LINK_HEADLOSS);
                            _buffer.AppendLine($"{id}: Flow={flow}, Headloss={headloss}");
                        }
                        catch { }
                    }
                }
            }
        }

        /// <summary>
        /// Salva o relatório gerado em um arquivo. Garante que Generate() seja chamado antes de salvar.
        /// </summary>
        public void Save(string path)
        {
            if (string.IsNullOrWhiteSpace(path)) throw new ArgumentException("path");
            if (_buffer.Length == 0) Generate();
            File.WriteAllText(path, _buffer.ToString());
        }

        /// <summary>
        /// Limpa o buffer interno do relatório.
        /// </summary>
        public void Clear()
        {
            _buffer.Clear();
        }

        /// <summary>
        /// Retorna o conteúdo do relatório como string.
        /// </summary>
        public string Summary() => _buffer.ToString();
    }
}
